[mappings]
LEFTMETA = "LCMD"
RIGHTMETA = "RCMD"
LEFTSHIFT = "LSHFT"
RIGHTSHIFT = "RSHFT"
LEFTCTRL = "LCTRL"
RIGHTCTRL = "RCTRL"
LEFTALT = "LALT"
RIGHTALT = "RALT"
ENTER = "ENT"
BACKSPACE = "BKSP"
SPACE = "SPC"
TAB = "TAB"
ESC = "ESC"
CAPSLOCK = "CAPS"
