[mappings]
LEFTMETA = "⌘"
RIGHTMETA = "⌘"
LEFTSHIFT = "⇧"
RIGHTSHIFT = "⇧"
LEFTCTRL = "^"
RIGHTCTRL = "^"
LEFTALT = "⎇"
RIGHTALT = "⎇"
ENTER = "↵"
BACKSPACE = "⌫"
SPACE = "␣"
TAB = "↹"
ESC = "ESC"
CAPSLOCK = "CAPS"
