pub fn map_char_key(key: &str, has_shift: bool) -> Option<&'static str> {
    match (key, has_shift) {
        ("1", true) => Some("!"),
        ("2", true) => Some("@"),
        ("3", true) => Some("#"),
        ("4", true) => Some("$"),
        ("5", true) => Some("%"),
        ("6", true) => Some("^"),
        ("7", true) => Some("&"),
        ("8", true) => Some("*"),
        ("9", true) => Some("("),
        ("0", true) => Some(")"),
        ("MINUS", false) => Some("-"),
        ("MINUS", true) => Some("_"),
        ("EQUAL", false) => Some("="),
        ("EQUAL", true) => Some("+"),
        ("LEFTBRACE", false) => Some("["),
        ("LEFTBRACE", true) => Some("{ "),
        ("RIGHTBRACE", false) => Some("]"),
        ("RIGHTBRACE", true) => Some("}"),
        ("BACKSLASH", false) => Some("\\"),
        ("BACKSLASH", true) => Some("|"),
        ("SEMICOLON", false) => Some(";"),
        ("SEMICOLON", true) => Some(":"),
        ("APOSTROPHE", false) => Some("'"),
        ("APOSTROPHE", true) => Some("\""),
        ("GRAVE", false) => Some("`"),
        ("GRAVE", true) => Some("~"),
        ("COMMA", false) => Some(","),
        ("COMMA", true) => Some("<"),
        ("DOT", false) => Some("."),
        ("DOT", true) => Some(">"),
        ("SLASH", false) => Some("/"),
        ("SLASH", true) => Some("?"),
        _ => None,
    }
}
